### ISSUE TITLE
Can't install to PCL via NUGET

### ISSUE THREAD

**Issue by mxstudios** [SuavePirate/BadgeView#1]
Had no problem installing to iOS and Android projects from NUGET, but got error when adding to the PCL:

Could not install package 'BadgeView 2017.10.17'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by SuavePirate** [comment]
That's because the PCL targets Profile 111 which is not compatible with profile 78 in some instances.
