### ISSUE TITLE
BadgeView is square on iOS

### ISSUE THREAD

**Issue by Morten-Kortermann-IT** [SuavePirate/BadgeView#2]
As the title says, I've added the badgeview to my project and it looks fine on Android but on iOS it is just a square box

**Comment by SuavePirate** [comment]
Seems like the typical Xamarin.Forms issue with the renderer getting linked out. Call `CircleViewRenderer.Initialize()` in your `AppDelegate` and it should clear the issue up.

**Comment by Morten-Kortermann-IT** [comment]
Perfect, thank you for the very prompt answer.
