### ISSUE TITLE
The Badge is showing a retagles instead a circle in Xamarin.Forms.IOS 

### ISSUE THREAD

**Issue by leonardosys4web** [SuavePirate/BadgeView#8]
I'm using  BadgeView.Shared.BadgeView the componente is showing a rectangle instead a circle on Iphone.

Version: 2017.10.17

      Android View:      
![image](https://user-images.githubusercontent.com/29409182/42289998-172cee34-7f99-11e8-89b5-aa7af1a58aa5.png)

Iphone View

![image](https://user-images.githubusercontent.com/29409182/42290266-98329cf8-7f9a-11e8-8f3e-ca20cac98da7.png)

**Comment by SuavePirate** [comment]
what version of Xamarin.Forms and did you initialize the renderer so it doesn't get linked out?

**Comment by leroygumede** [comment]
Fixed it by adding `CircleViewRenderer.Initialize();` in my native projects
